### ISSUE TITLE
Output folders are misplaced after switching to batch_connect model

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/bc_comsol_server#1] opened 2017-02-08 15:07 UTC
The output folder for COMSOL server apps appear to be in the wrong place.

See the underlined portion of the image below. The `.comsol` folder is located in my HOME directory, but the vncsim app appears to be setting HOME on the output path to an folder in the `awesim/data` folder. 

At some point the COMSOL_PREFSDIR [assigned here](https://github.com/OSC/bc_comsol_server/blob/master/template/xstartup), is being appended to the individual app's output path.

![comsoloutput](https://cloud.githubusercontent.com/assets/2374718/22742463/d494d6dc-ede4-11e6-93e8-1275493731c7.png)

This has been tested in HeatSinkSim, but appears to affect all apps using `bc_comsol_server`.

**Comment by brianmcmichael** [comment] 2017-02-08 15:47
There is a possibility that this error is occurring inside of the COMSOL apps themselves.

The app route structure changed after the update to the `bc_` style apps, and there weren't any corresponding modifications to the underlying AltaSim apps. I am concerned that there may be paths coded into those apps that didn't get updated.

**Comment by brianmcmichael** [comment] 2017-02-08 19:37
Initial bugfix dropped at https://github.com/OSC/bc_comsol_server/commit/fa1db8bef4ac0092d37b24059561615d70b76e35 and released as `v0.0.2`

Per @nickjer there is still room for improvement here.

> A more permanent solution is that the apps themselves use either the COMSOL_PREFSDIR or HOME environment variable. But I am not sure what security restrictions Java enforces for that. I tried to default the comsol server Java with no security permissions.

Also, after submitting a job with the same parameters as a job I had killed I received the following error:

![running](https://cloud.githubusercontent.com/assets/2374718/22753969/ee0ff890-ee0b-11e6-8919-71eb48493783.png)

I'm not sure if this was a fluke or if there is a file being left behind in the prefsdir that conflicts. Creating a new job with different parameters submitted successfully.

**Comment by nickjer** [comment] 2017-02-13 14:15
@brianmcmichael: is that last bug you encountered fixed? or is this issue still open?

**Comment by brianmcmichael** [comment] 2017-02-15 15:03
I'm still experiencing this issue.

**Comment by nickjer** [comment] 2017-02-15 17:50
Ah, this is a "bug" in the design of the app by AltaSim. The `*.mph` file as well as the corresponding `*.status` and `*.log` files are named after the parameters that make up the job. So when you submit a job with the exact same parameters, the file `*.status` with the same name says it is still running so it blocks you.

This is more of an issue for AltaSim, and even then I am not sure if they believe this is an issue or is intended behavior. So closing this here.

**Closed as completed by nickjer** 2017-02-15 17:50 UTC
Labels: bug
