### ISSUE TITLE
Error when loading HeatSinkSim app via `rnode`

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/bc_comsol_server#2] opened 2017-02-15 14:46 UTC
To replicate, access COMSOL server at apps.awesim.org. 
Connect via the `rnode` proxy option. 
After logging in, the app hangs and provides a `412` error when loading the HeatSinkSim app.
This error does not occur when accessing via the SSH tunnel.

![hss](https://cloud.githubusercontent.com/assets/2374718/22979099/25ffa118-f363-11e6-85eb-5326231dea56.png)

**Comment by nickjer** [comment] 2017-02-16 17:07
This may be due to OOD infrastructure changes that have yet to be incorporated into the production servers. Does this appear on apps-test.awesim.org?

**Comment by nickjer** [comment] 2017-02-16 18:01
I am able to reproduce this error in apps.awesim.org but not in apps-test.awesim.org. So this is probably related to the infrastructure updates. This will be fixed whenever we push the infrastructure updates to production.

**Comment by nickjer** [comment] 2018-01-24 15:36
Closing this until it is observed again.

**Closed as completed by nickjer** 2018-01-24 15:36 UTC
